version: '2'

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb-G3
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - /home/vmarechal/conf/.env/mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi-G3
    hostname: glpi
    ports:
      - "8080:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    env_file:
      - /home/vmarechal/conf/.env/glpi.env 
    restart: always
  
#PORTAINER Container
  portainer:
    container_name: portainer-G3
    image: 'portainer/portainer-ce:latest'
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/vmarechal/portainer/:/data
    ports:
        - 8081:9000

#NEXTCLOUD Container  
  nextcloud:
    container_name: nextcloud-G3
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    links:
      - mariadb
    volumes:
      - /home/vmarechal/nextcloud:/var/www/html
    env_file:
      - /home/vmarechal/conf/.env/nextcloud.env

